<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="gobilda_robot" params="prefix">

    <!-- Robot Parameters -->
    <xacro:property name="PI" value="3.14159265"/>
    <xacro:property name="body_length" value="0.5"/>
    <xacro:property name="body_width" value="0.386"/>
    <xacro:property name="body_height" value="0.1"/>
    <xacro:property name="body_density" value="7850.0"/> <!-- Steel -->
    <xacro:property name="body_mass" value="${body_density * body_length * body_height * body_width}"/>
    <xacro:property name="body_inertia_x" value="${1.0/12.0 * body_mass * (body_height*body_height + body_width*body_width)}"/>
    <xacro:property name="body_inertia_y" value="${1.0/12.0 * body_mass * (body_length*body_length + body_height*body_height)}"/>
    <xacro:property name="body_inertia_z" value="${1.0/12.0 * body_mass * (body_length*body_length + body_width*body_width)}"/>

    <xacro:property name="wheel_radius" value="0.0485"/>
    <xacro:property name="wheel_width" value="0.038"/>
    <xacro:property name="wheel_separation" value="${body_width + wheel_width}"/>
    <xacro:property name="wheel_offset_x" value="0.1"/>
    <xacro:property name="wheel_offset_y" value="0.09"/>
    <xacro:property name="wheel_density" value="900"/> <!-- Ruber -->
    <xacro:property name="wheel_mass" value="${wheel_density * PI * wheel_radius * wheel_radius * wheel_width}"/>
    <xacro:property name="wheel_inertia_x" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_y" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_z" value="${1.0/2.0 * wheel_mass * wheel_radius * wheel_radius}"/>

    <xacro:property name="lidar_offset_x" value="0.1"/>
    <xacro:property name="lidar_offset_y" value="0.0"/>
    <xacro:property name="lidar_offset_z" value="0.03"/>

    <xacro:property name="camera_offset_x" value="0.192"/>
    <xacro:property name="camera_offset_y" value="0.013"/>
    <xacro:property name="camera_offset_z" value="0.0015"/>

    <xacro:property name="imu_offset_x" value="0.192"/>
    <xacro:property name="imu_offset_y" value="0.013"/>
    <xacro:property name="imu_offset_z" value="0.0015"/>

    <!-- Control Parameters -->    
    <xacro:property name="max_linear_acceleration" value="10"/>

    <!-- Links -->

    <!-- Body Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        
        <inertial>
            <mass value="10"/>
            <inertia ixx="${body_inertia_x}" ixy="0.0" ixz="0.0" iyy="${body_inertia_y}" iyz="0" izz="${body_inertia_z}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
        <visual>
            <origin xyz="-${wheel_offset_x} 0.27 -0.01" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="-${wheel_offset_x} 0.27 -0.01" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
       
        <inertial>
            <mass value="2"/>
            <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0" iyy="${wheel_inertia_y}" iyz="0" izz="${wheel_inertia_z}"/>
            <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
        </inertial>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
        <visual>
            <origin xyz="-${wheel_offset_x} -${wheel_offset_y} -0.01" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="-${wheel_offset_x} -${wheel_offset_y} -0.01" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        
        <inertial>
            <mass value="2"/>
            <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0" iyy="${wheel_inertia_y}" iyz="0" izz="${wheel_inertia_z}"/>
            <origin xyz="0.0 0.0 0.0" rpy="1.570795 0.0 0.0"/>
        </inertial>
    </link>

    <!-- Laser -->
    <link name="laser">
        <visual>
            <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>
    </link>

    <!-- Camera -->
    <link name="camera">
        <visual>
	    <origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="0 0 0"/>
	    <geometry>
		<box size="0.024 0.099 0.031"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="0 0 0"/>
            <geometry>
                <box size="0.024 0.099 0.031"/>
            </geometry>
        </collision>
    </link>

    <!-- IMU -->
    <link name="imu">
        <visual>
            <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0"/>
            <geometry>
                <box size="0.024 0.099 0.031"/>
            </geometry>
        </visual>

        <collision>
		<origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0"/>
            <geometry>
                <box size="0.024 0.099 0.031"/>
            </geometry>
        </collision>
</link>0


    <!-- Joints -->

    <!-- Left Wheel Joint -->
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="-${wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Right Wheel Joint -->
    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="-${wheel_offset_x} ${-wheel_offset_y} 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Lidar Joint (fixed) -->
    <joint name="lidar_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="laser"/>
    </joint>

    <!-- Camera Joint (fixed) -->
    <joint name="camera_joint" type="fixed">
	<origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="3.14159265 0 0"/>
	<parent link="base_link"/>
	<child link="camera"/>
    </joint>

    <!-- IMU Joint (fixed) -->
    <joint name="imu_joint" type="fixed">
        <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="3.14159265 0 0"/>
        <parent link="base_link"/>
        <child link="imu"/>
    </joint>

</xacro:macro>
</robot>
